version: "3"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - backend-network
    volumes:
      - db:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend-network
    volumes:
      - cache:/data
    restart: unless-stopped

networks:
  backend-network:
    driver: bridge

volumes:
  db:
    driver: local
  cache:
    driver: local
